name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (for Vite build)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose appropriate Node.js version for Vite

      - name: Install Dependencies
        run: |
          cd public
          npm install  # Assuming package.json exists in the public folder

      - name: Build Vite Frontend
        run: |
          cd public
          npm run build  # Assuming Vite build script is in package.json

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vite-web-build
          path: public/dist  # Assuming build output is in the dist folder

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Download Vite Web Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: vite-web-build
          path: vite-web-build
  
      - name: Verify Downloaded Artifact
        run: |
          echo "Verifying downloaded artifact..."
          ls -la  # This will show the current directory's contents
          ls -la vite-web-build || echo "vite-web-build directory doesn't exist"  # Added check for existence of the directory
  
      - name: Prepare Build Context
        run: |
          mkdir -p build/web
          cp -r vite-web-build/* build/web  # Copy files from the downloaded artifact to the build/web folder
          echo "Build context prepared:"
          ls -la build/web  # Verify the files are in the build/web directory
  
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
  
      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
  
      - name: Build Docker Image for API
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/navicare-ai-api \
            -f Dockerfile .
  
      - name: Build Docker Image for Vite Web App
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/vite-web-app \
            -f Dockerfile.web .
  
      - name: Verify Files in Docker Image
        run: |
          docker run us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/vite-web-app ls -l /usr/share/nginx/html
        
      - name: Push Docker Images
        run: |
          docker push us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/navicare-ai-api
          docker push us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/vite-web-app

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy API to Cloud Run
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: |
          gcloud run deploy navicare-ai-api \
            --image us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/navicare-ai-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --update-env-vars XAI_API_KEY=$XAI_API_KEY

      - name: Deploy Vite Web App to Cloud Run
        run: |
          gcloud run deploy vite-web-app \
            --image us-central1-docker.pkg.dev/navicare-ai/navicare-ai-docker-repo/vite-web-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
